### ISSUE TITLE
release v1.0.0 TODO

### ISSUE THREAD

**Issue by mx2s** [mxss/micron#21]
TODO before release:
- [ ] #19 Simplify methods to get parameters from (not only query but also a body of the request)
- [ ] #20 camelCase parameters instead of snake_case
- [ ] #18 template swagger file
...
